---
- hosts: all
  tasks:
  - name: Ensure `~/software` directory exists
    file:
      path: ~/software
      state: directory
      mode: "755"
  - name: Install Development Tools
    unarchive:
      src: "{{ item }}"
      dest: ~/software/
      remote_src: yes
    with_items:
      - https://github.com/JetBrains/kotlin/releases/download/v1.4.32/kotlin-compiler-1.4.32.zip
