
name: CI
on:
  push:
  workflow_dispatch:

jobs:
  run-in-container-deb:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        version: [latest, rolling, devel]
    steps:
    - uses: actions/checkout@v2
    - name: Run Ansible
      run: bash repro.sh ${{ matrix.version }}